version: '3.8'
services:
  stats-server:
    build: stats/server
    image: stats
    container_name: stats_server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  ewm-server:
    build: main_server
    image: main_server
    container_name: main_server-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-main_server-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
