DROP TABLE IF EXISTS comments_admin, comments, requests, compilation_events, compilations, events,
    locations, categories, users;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255)                            NOT NULL UNIQUE,
    name  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) UNIQUE,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat FLOAT4,
    lon FLOAT4,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 INT GENERATED ALWAYS AS IDENTITY,
    initiator          INT           NOT NULL,
    annotation         VARCHAR(1000) NOT NULL,
    category           INT           NOT NULL,
    description        VARCHAR(1000) NOT NULL,
    event_date         TIMESTAMP     NOT NULL,
    location           INT           NOT NULL,
    paid               BOOLEAN       NOT NULL,
    participant_limit  INT,
    request_moderation BOOLEAN       NOT NULL,
    title              VARCHAR(100)  NOT NULL,
    create_on          TIMESTAMP     NOT NULL,
    published_on       TIMESTAMP,
    state              VARCHAR(10)   NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id),
    CONSTRAINT fk_initiator FOREIGN KEY (initiator) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_category FOREIGN KEY (category) REFERENCES categories (id) ON DELETE CASCADE,
    CONSTRAINT fk_location FOREIGN KEY (location) REFERENCES locations (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created   TIMESTAMP,
    event     BIGINT references events (id),
    requester BIGINT references users (id),
    status    VARCHAR(255),
    CONSTRAINT pk_requests PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN,
    title  VARCHAR(255),
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id BIGINT REFERENCES compilations (id),
    event_id       BIGINT REFERENCES events (id),
    CONSTRAINT ce_pk PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id              INT GENERATED ALWAYS AS IDENTITY,
    comment         VARCHAR(7000) NOT NULL,
    commentator     INT           NOT NULL,
    commented_event INT           NOT NULL,
    create_on       TIMESTAMP     NOT NULL,
    published_on    TIMESTAMP,
    edit_on         TIMESTAMP,
    status          VARCHAR(20)       NOT NULL,
    comment_admin   VARCHAR(200),
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_commentator FOREIGN KEY (commentator) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_commented_event FOREIGN KEY (commented_event) REFERENCES events (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments_admin
(
    id            INT GENERATED ALWAYS AS IDENTITY,
    comment_id    INT,
    comment_admin VARCHAR(500),
    created_on    TIMESTAMP,
    CONSTRAINT pk_comments_admin PRIMARY KEY (id),
    CONSTRAINT fk_comment_id FOREIGN KEY (comment_id) REFERENCES comments (id) ON DELETE CASCADE
);

